### ISSUE TITLE
[Feature]: Support ConsistencyLevel in milvus go sdk

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus-sdk-go#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Milvus collection has an attribute called `ConsistencyLevel` to control search/query consistency level.
Go SDK shall support this feature.

### Describe the solution you'd like.

- [x] Add ConsistencyLevel definition #264 
- [x] Support specify ConsistencyLevel when create collection #264
- [x] Support ConsistencyLevel logic in search/query logic #289

**Comment by zhyq0520** [comment]
Support ConsistencyLevel logic in search/query logic
--------------------------------
hi,  will this be supported?
